{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-1389",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://www.ibm.com/support/docview.wss?uid=swg22013531",
          "name": "http://www.ibm.com/support/docview.wss?uid=swg22013531",
          "refsource": "CONFIRM"
        },
        {
          "url": "http://www.securityfocus.com/bid/104026",
          "name": "104026",
          "refsource": "BID"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/138213",
          "name": "ibm-api-cve20181389-info-mod(138213)",
          "refsource": "XF"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM API Connect 5.0.0.0 through 5.0.8.2 is impacted by generated LoopBack APIs for a Model using the BelongsTo/HasMany relationship allowing unauthorized modification of information. IBM X-Force ID: 138213."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-04-30T14:29Z",
  "lastModifiedDate": "2018-05-03T01:29Z"
}