{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2017-2592",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html",
          "name": "http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html",
          "refsource": "CONFIRM"
        },
        {
          "url": "http://rhn.redhat.com/errata/RHSA-2017-0300.html",
          "name": "RHSA-2017:0300",
          "refsource": "REDHAT"
        },
        {
          "url": "http://rhn.redhat.com/errata/RHSA-2017-0435.html",
          "name": "RHSA-2017:0435",
          "refsource": "REDHAT"
        },
        {
          "url": "http://www.securityfocus.com/bid/95827",
          "name": "95827",
          "refsource": "BID"
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2017:0300",
          "name": "https://access.redhat.com/errata/RHSA-2017:0300",
          "refsource": "CONFIRM"
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2017:0435",
          "name": "https://access.redhat.com/errata/RHSA-2017:0435",
          "refsource": "CONFIRM"
        },
        {
          "url": "https://bugs.launchpad.net/keystonemiddleware/+bug/1628031",
          "name": "https://bugs.launchpad.net/keystonemiddleware/+bug/1628031",
          "refsource": "MISC"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592",
          "refsource": "CONFIRM"
        },
        {
          "url": "https://review.openstack.org/#/c/425730/",
          "name": "https://review.openstack.org/#/c/425730/",
          "refsource": "MISC"
        },
        {
          "url": "https://review.openstack.org/#/c/425732/",
          "name": "https://review.openstack.org/#/c/425732/",
          "refsource": "MISC"
        },
        {
          "url": "https://review.openstack.org/#/c/425734/",
          "name": "https://review.openstack.org/#/c/425734/",
          "refsource": "MISC"
        },
        {
          "url": "https://usn.ubuntu.com/3666-1/",
          "name": "USN-3666-1",
          "refsource": "UBUNTU"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulnerable to an information disclosure. Software using the CatchError class could include sensitive values in a traceback's error message. System users could exploit this flaw to obtain sensitive information from OpenStack component error logs (for example, keystone tokens)."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-05-08T17:29Z",
  "lastModifiedDate": "2018-06-02T01:29Z"
}