{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2017-1768",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://www.ibm.com/support/docview.wss?uid=swg22016515",
          "name": "http://www.ibm.com/support/docview.wss?uid=swg22016515",
          "refsource": "CONFIRM"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/136471",
          "name": "ibm-guardium-cve20171768-info-disc(136471)",
          "refsource": "XF"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM Security Guardium Big Data Intelligence (SonarG) 3.1 generates an error message that includes sensitive information about its environment, users, or associated data. IBM X-Force ID: 136471."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-05-29T13:29Z",
  "lastModifiedDate": "2018-05-29T13:29Z"
}