{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2016-10525",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://github.com/dwyl/hapi-auth-jwt2/issues/111",
          "name": "https://github.com/dwyl/hapi-auth-jwt2/issues/111",
          "refsource": "MISC"
        },
        {
          "url": "https://github.com/dwyl/hapi-auth-jwt2/pull/112",
          "name": "https://github.com/dwyl/hapi-auth-jwt2/pull/112",
          "refsource": "MISC"
        },
        {
          "url": "https://nodesecurity.io/advisories/81",
          "name": "https://nodesecurity.io/advisories/81",
          "refsource": "MISC"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "When attempting to allow authentication mode `try` in hapi, hapi-auth-jwt2 version 5.1.1 introduced an issue whereby people could bypass authentication."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-05-29T20:29Z",
  "lastModifiedDate": "2018-05-29T20:29Z"
}